name: MacBook Price Checker

on:
  schedule:
    - cron: '0 */6 * * *' # רץ כל 6 שעות
  workflow_dispatch: # כפתור להרצה ידנית

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium # השורה החדשה שהוספנו!

      - name: Run the script
        run: python scraper.py
