name: MacBook Price Checker

on:
  workflow_dispatch: # מאפשר לך להריץ ידנית בלחיצת כפתור

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install duckduckgo_search

      - name: Run the script
        run: python scraper.py
